"""
blender_export.py — Generates a standalone Blender Python script that
builds a 3D reference scene (one textured plane per exported view/section
image) from the output of compositor.export_split_views().

This module never imports bpy — it only computes plane placements and
renders the *text* of a script that imports bpy and runs inside Blender.
"""

# Per-view plane rotation (Blender XYZ Euler, degrees). Hardcoded lookup,
# NOT a derived formula — this codebase has been bitten twice assuming a
# formula for per-view axis handling when a lookup table was required (see
# _RIB_MARKER_AXIS in compositor.py). Confirmed empirically against one
# hand-built reference .blend for one car model — see the split-view-export
# branch's PR description before trusting this on a very different model.
_VIEW_ROTATIONS_DEG = {
    "left":   (90, 0, 0),
    "right":  (90, 0, -180),
    "top":    (-180, 0, 90),
    "front":  (90, 0, 90),
    "back":   (90, 0, 90),
    "bottom": (0, 0, 90),
}
_SECTION_ROTATION_DEG = _VIEW_ROTATIONS_DEG["front"]  # sections cut
    # perpendicular to the same depth axis front/back cap.

# UNCONFIRMED sign — the one hand-built reference example was left/right
# symmetric, so this was never actually tested. Flip to -1 if visual
# verification against a real, asymmetric render shows it's backwards.
# Single point of change deliberately kept here, not duplicated inline.
_LEFT_Y_SIGN = 1


def compute_plane_specs(saved_keys, layout):
    """saved_keys: iterable of keys from export_split_views()'s `saved`
    dict (e.g. {"front", "left", "top", "section_1"}). layout: the dict
    returned alongside `saved`.

    Returns a list of {"name", "filename", "location", "rotation_deg"}
    dicts, one per plane. Only emits a spec for a view actually present in
    saved_keys, mirroring export_split_views' own per-view filtering.
    filename matches the ZIP entry name convention ("front.png",
    "section_1.png"), not the on-disk temp path.
    """
    saved_keys = set(saved_keys)
    max_dim = float(layout["max_dim"])
    half_w = float(layout["W"]) / max_dim / 2
    half_h = float(layout["H"]) / max_dim / 2
    half_d = float(layout["D"]) / max_dim / 2

    view_offsets = {
        "front":  (half_d, 0, 0),
        "back":   (-half_d, 0, 0),
        "top":    (0, 0, half_h),
        "bottom": (0, 0, -half_h),
        "left":   (0, _LEFT_Y_SIGN * half_w, 0),
        "right":  (0, -_LEFT_Y_SIGN * half_w, 0),
    }

    specs = []
    for name in ("front", "back", "left", "right", "top", "bottom"):
        if name not in saved_keys:
            continue
        specs.append({
            "name": name,
            "filename": f"{name}.png",
            "location": view_offsets[name],
            "rotation_deg": _VIEW_ROTATIONS_DEG[name],
        })

    rib_fracs = layout.get("rib_fracs") or []
    for i, frac in enumerate(rib_fracs):
        name = f"section_{i + 1}"
        if name not in saved_keys:
            continue
        x = -half_d + frac * (2 * half_d)
        specs.append({
            "name": name,
            "filename": f"{name}.png",
            "location": (x, 0, 0),
            "rotation_deg": _SECTION_ROTATION_DEG,
        })

    return specs


_SCRIPT_TEMPLATE = '''"""
build_reference_scene.py, auto-generated by Ortho. Builds a 3D reference
scene of textured image planes from the PNGs exported alongside this
script. Open this file from the unzipped folder via Blender's Scripting
tab (File > Open, not a pasted/new text block) then Run Script, or run it
headless: blender --background --python build_reference_scene.py

If the images can't be found automatically, set IMAGE_DIR_OVERRIDE below
to the absolute path of the folder containing this script and the PNGs.
"""
import bpy
import os
import math

IMAGE_DIR_OVERRIDE = None

PLANES = {planes!r}


def _image_dir():
    if IMAGE_DIR_OVERRIDE:
        return IMAGE_DIR_OVERRIDE
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except NameError:
        pass
    text = getattr(bpy.context.space_data, "text", None)
    if text and text.filepath:
        return os.path.dirname(bpy.path.abspath(text.filepath))
    raise RuntimeError(
        "Could not locate this script's folder. Open this .py file via "
        "File > Open in Blender's Text Editor (not a pasted/new text "
        "block), or set IMAGE_DIR_OVERRIDE at the top of this script.")


def _make_image_plane(name, image_path, location, rotation_deg):
    mesh = bpy.data.meshes.new(name + "_mesh")
    verts = [(-0.5, -0.5, 0), (0.5, -0.5, 0), (0.5, 0.5, 0), (-0.5, 0.5, 0)]
    mesh.from_pydata(verts, [], [[0, 1, 2, 3]])
    mesh.uv_layers.new()
    uv = mesh.uv_layers[0].data
    for i, co in enumerate([(0, 0), (1, 0), (1, 1), (0, 1)]):
        uv[i].uv = co
    mesh.update()

    obj = bpy.data.objects.new(name, mesh)
    obj.location = location
    obj.rotation_euler = tuple(math.radians(d) for d in rotation_deg)
    bpy.context.collection.objects.link(obj)

    mat = bpy.data.materials.new(name + "_mat")
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    bsdf = next(n for n in nodes if n.type == "BSDF_PRINCIPLED")
    tex = nodes.new("ShaderNodeTexImage")
    tex.image = bpy.data.images.load(image_path, check_existing=True)
    tex.interpolation = "Linear"
    links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
    links.new(tex.outputs["Alpha"], bsdf.inputs["Alpha"])
    mat.blend_method = "HASHED"
    mat.use_backface_culling = False
    obj.data.materials.append(mat)
    return obj


def main():
    img_dir = _image_dir()
    built = 0
    for spec in PLANES:
        path = os.path.join(img_dir, spec["filename"])
        if not os.path.exists(path):
            print(f"[skip] missing image: {{path}}")
            continue
        _make_image_plane(spec["name"], path, spec["location"], spec["rotation_deg"])
        built += 1
    print(f"Built {{built}} reference plane(s).")


main()
'''


def render_script(plane_specs):
    """Renders the full standalone .py source text, with plane_specs
    baked in as a literal constant near the top."""
    return _SCRIPT_TEMPLATE.format(planes=plane_specs)
